name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubutntu-latest
        steps:
            - name: Welcome message
              run: echo "My first Github Actions Job"

            - name: List files
              run: ls

            - name: Read file
              run: cat README.md